language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t vijay20886/selenium1 -f Dockerfile.dev .

script:
  - docker run -e CI=true vijay20886/selenium1 npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker3"
  env: "Docker3-env"
  bucket_name: "elasticbeanstalk-eu-west-2-795670526764"
  bucket_path: "docker3"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
